environment:
  global:
    wxWidgets_ROOT_DIR: C:\wxWidgets-3.1.0\

os:
  - Visual Studio 2013
  - Visual Studio 2015

install:
  - choco install wxwidgets

build_script:
  - mkdir build
  - cd build 
  - cmake ..
  - cmake --build .

