language: cpp
dist: trusty
sudo: required

os:
  - linux
  - osx


# install build dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libwxgtk3.0-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install wxmac; fi


# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
