language: cpp
dist: trusty
sudo: required

# install build dependencies
before_install:
  - sudo apt-get install libwxgtk3.0-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
